# Generated by Django 3.2 on 2022-04-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='namme',
            new_name='name',
        ),
    ]
