# Generated by Django 3.2 on 2022-04-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_namme_orderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
