# Generated by Django 3.2 on 2022-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
